#
# Copyright (C) 2026 The Android Open Source Project
# Copyright (C) 2026 SebaUbuntu's TWRP Device Tree Generator
# Copyright (C) 2019-Present A-Team Digital Solutions
# Copyright (C) 2024 sosRR
#

DEVICE_PREBUILT_PATH := device/motorola/mona/prebuilt

# OrangeFox Build Configuration
OF_MAINTAINER := PizzaG
FOX_BUILD_TYPE := A-Team_v0.01
FOX_VERSION := 12.1
#FOX_MAINTAINER_PATCH_VERSION := 12
OF_AB_DEVICE_WITH_RECOVERY_PARTITION := 1
OF_FLASHLIGHT_ENABLE := 1
OF_HIDE_NOTCH := 1
OF_USE_LOCKSCREEN_BUTTON := 1
FOX_ENABLE_APP_MANAGER := 1
FOX_REMOVE_AAPT := 0
OF_FORCE_PREBUILT_KERNEL := 1
OF_DEFAULT_KEYMASTER_VERSION := 4.1
OF_DISABLE_MIUI_SPECIFIC_FEATURES := 1
OF_NO_ADDITIONAL_MIUI_PROPS_CHECK := 1
OF_DONT_PATCH_ENCRYPTED_DEVICE := 1
FOX_USE_BASH_SHELL := 1
FOX_USE_TAR_BINARY := 1
FOX_USE_SED_BINARY := 1
FOX_USE_XZ_UTILS := 1
FOX_USE_LZ4_UTILS := 1
OF_NO_TREBLE_COMPATIBILITY_CHECK := 1
OF_STATUS_INDENT_LEFT := 64
OF_STATUS_INDENT_RIGHT := 64
OF_ADVANCED_SECURITY := 1
FOX_DELETE_AROMAFM := 0
OF_RUN_POST_FORMAT_PROCESS := 1
OF_FBE_METADATA_MOUNT_IGNORE := 1
OF_ENABLE_LPTOOLS := 1
OF_UNBIND_SDCARD_F2FS := 1
OF_KEEP_DM_VERITY := 1
OF_FIX_OTA_UPDATE_MANUAL_FLASH_ERROR := 1
OF_SUPPORT_ALL_PAYLOAD_OTA_UPDATES := 1
OF_ENABLE_USB_STORAGE := 1
FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER := 1
OF_SUPPORT_OZIP_DECRYPTION := 1
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := 1
OF_USE_MAGISKBOOT := 1

# OrangeFox Maintanier PNG - 192*192
PRODUCT_COPY_FILES += \
        $(DEVICE_PREBUILT_PATH)/maintainer.png:recovery/root/twres/images/Default/About/maintainer.png